/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RoomsCreateRouteImport } from './routes/rooms/create'
import { Route as RoomsIdIndexRouteImport } from './routes/rooms/$id/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsCreateRoute = RoomsCreateRouteImport.update({
  id: '/rooms/create',
  path: '/rooms/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdIndexRoute = RoomsIdIndexRouteImport.update({
  id: '/rooms/$id/',
  path: '/rooms/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$id/': typeof RoomsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$id': typeof RoomsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$id/': typeof RoomsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/rooms/create'
    | '/rooms/'
    | '/rooms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/profile' | '/rooms/create' | '/rooms' | '/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/profile'
    | '/rooms/create'
    | '/rooms/'
    | '/rooms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  RoomsCreateRoute: typeof RoomsCreateRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  RoomsIdIndexRoute: typeof RoomsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/create': {
      id: '/rooms/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof RoomsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/': {
      id: '/rooms/$id/'
      path: '/rooms/$id'
      fullPath: '/rooms/$id/'
      preLoaderRoute: typeof RoomsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  RoomsCreateRoute: RoomsCreateRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  RoomsIdIndexRoute: RoomsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
