/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as AiIndexRouteImport } from './routes/ai/index'
import { Route as RoomsCreateRouteImport } from './routes/rooms/create'
import { Route as AiSuggestionsRouteImport } from './routes/ai/suggestions'
import { Route as AiInsightsRouteImport } from './routes/ai/insights'
import { Route as AiHistoryRouteImport } from './routes/ai/history'
import { Route as AiExercisesRouteImport } from './routes/ai/exercises'
import { Route as AiChatRouteImport } from './routes/ai/chat'
import { Route as RoomsIdIndexRouteImport } from './routes/rooms/$id/index'
import { Route as RoomsIdSettingsRouteImport } from './routes/rooms/$id/settings'
import { Route as RoomsIdParticipantsRouteImport } from './routes/rooms/$id/participants'
import { Route as RoomsIdOverviewRouteImport } from './routes/rooms/$id/overview'
import { Route as RoomsIdInviteRouteImport } from './routes/rooms/$id/invite'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsCreateRoute = RoomsCreateRouteImport.update({
  id: '/rooms/create',
  path: '/rooms/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSuggestionsRoute = AiSuggestionsRouteImport.update({
  id: '/ai/suggestions',
  path: '/ai/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai/insights',
  path: '/ai/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHistoryRoute = AiHistoryRouteImport.update({
  id: '/ai/history',
  path: '/ai/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AiExercisesRoute = AiExercisesRouteImport.update({
  id: '/ai/exercises',
  path: '/ai/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdIndexRoute = RoomsIdIndexRouteImport.update({
  id: '/rooms/$id/',
  path: '/rooms/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdSettingsRoute = RoomsIdSettingsRouteImport.update({
  id: '/rooms/$id/settings',
  path: '/rooms/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdParticipantsRoute = RoomsIdParticipantsRouteImport.update({
  id: '/rooms/$id/participants',
  path: '/rooms/$id/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdOverviewRoute = RoomsIdOverviewRouteImport.update({
  id: '/rooms/$id/overview',
  path: '/rooms/$id/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdInviteRoute = RoomsIdInviteRouteImport.update({
  id: '/rooms/$id/invite',
  path: '/rooms/$id/invite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/ai/chat': typeof AiChatRoute
  '/ai/exercises': typeof AiExercisesRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/suggestions': typeof AiSuggestionsRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/ai/': typeof AiIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$id/invite': typeof RoomsIdInviteRoute
  '/rooms/$id/overview': typeof RoomsIdOverviewRoute
  '/rooms/$id/participants': typeof RoomsIdParticipantsRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id/': typeof RoomsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/ai/chat': typeof AiChatRoute
  '/ai/exercises': typeof AiExercisesRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/suggestions': typeof AiSuggestionsRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/ai': typeof AiIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$id/invite': typeof RoomsIdInviteRoute
  '/rooms/$id/overview': typeof RoomsIdOverviewRoute
  '/rooms/$id/participants': typeof RoomsIdParticipantsRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id': typeof RoomsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/ai/chat': typeof AiChatRoute
  '/ai/exercises': typeof AiExercisesRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/suggestions': typeof AiSuggestionsRoute
  '/rooms/create': typeof RoomsCreateRoute
  '/ai/': typeof AiIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$id/invite': typeof RoomsIdInviteRoute
  '/rooms/$id/overview': typeof RoomsIdOverviewRoute
  '/rooms/$id/participants': typeof RoomsIdParticipantsRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id/': typeof RoomsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/ai/chat'
    | '/ai/exercises'
    | '/ai/history'
    | '/ai/insights'
    | '/ai/suggestions'
    | '/rooms/create'
    | '/ai/'
    | '/rooms/'
    | '/rooms/$id/invite'
    | '/rooms/$id/overview'
    | '/rooms/$id/participants'
    | '/rooms/$id/settings'
    | '/rooms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/ai/chat'
    | '/ai/exercises'
    | '/ai/history'
    | '/ai/insights'
    | '/ai/suggestions'
    | '/rooms/create'
    | '/ai'
    | '/rooms'
    | '/rooms/$id/invite'
    | '/rooms/$id/overview'
    | '/rooms/$id/participants'
    | '/rooms/$id/settings'
    | '/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/profile'
    | '/ai/chat'
    | '/ai/exercises'
    | '/ai/history'
    | '/ai/insights'
    | '/ai/suggestions'
    | '/rooms/create'
    | '/ai/'
    | '/rooms/'
    | '/rooms/$id/invite'
    | '/rooms/$id/overview'
    | '/rooms/$id/participants'
    | '/rooms/$id/settings'
    | '/rooms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  AiChatRoute: typeof AiChatRoute
  AiExercisesRoute: typeof AiExercisesRoute
  AiHistoryRoute: typeof AiHistoryRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiSuggestionsRoute: typeof AiSuggestionsRoute
  RoomsCreateRoute: typeof RoomsCreateRoute
  AiIndexRoute: typeof AiIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  RoomsIdInviteRoute: typeof RoomsIdInviteRoute
  RoomsIdOverviewRoute: typeof RoomsIdOverviewRoute
  RoomsIdParticipantsRoute: typeof RoomsIdParticipantsRoute
  RoomsIdSettingsRoute: typeof RoomsIdSettingsRoute
  RoomsIdIndexRoute: typeof RoomsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/create': {
      id: '/rooms/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof RoomsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/suggestions': {
      id: '/ai/suggestions'
      path: '/ai/suggestions'
      fullPath: '/ai/suggestions'
      preLoaderRoute: typeof AiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/insights': {
      id: '/ai/insights'
      path: '/ai/insights'
      fullPath: '/ai/insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/history': {
      id: '/ai/history'
      path: '/ai/history'
      fullPath: '/ai/history'
      preLoaderRoute: typeof AiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/exercises': {
      id: '/ai/exercises'
      path: '/ai/exercises'
      fullPath: '/ai/exercises'
      preLoaderRoute: typeof AiExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/': {
      id: '/rooms/$id/'
      path: '/rooms/$id'
      fullPath: '/rooms/$id/'
      preLoaderRoute: typeof RoomsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/settings': {
      id: '/rooms/$id/settings'
      path: '/rooms/$id/settings'
      fullPath: '/rooms/$id/settings'
      preLoaderRoute: typeof RoomsIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/participants': {
      id: '/rooms/$id/participants'
      path: '/rooms/$id/participants'
      fullPath: '/rooms/$id/participants'
      preLoaderRoute: typeof RoomsIdParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/overview': {
      id: '/rooms/$id/overview'
      path: '/rooms/$id/overview'
      fullPath: '/rooms/$id/overview'
      preLoaderRoute: typeof RoomsIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/invite': {
      id: '/rooms/$id/invite'
      path: '/rooms/$id/invite'
      fullPath: '/rooms/$id/invite'
      preLoaderRoute: typeof RoomsIdInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  AiChatRoute: AiChatRoute,
  AiExercisesRoute: AiExercisesRoute,
  AiHistoryRoute: AiHistoryRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiSuggestionsRoute: AiSuggestionsRoute,
  RoomsCreateRoute: RoomsCreateRoute,
  AiIndexRoute: AiIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  RoomsIdInviteRoute: RoomsIdInviteRoute,
  RoomsIdOverviewRoute: RoomsIdOverviewRoute,
  RoomsIdParticipantsRoute: RoomsIdParticipantsRoute,
  RoomsIdSettingsRoute: RoomsIdSettingsRoute,
  RoomsIdIndexRoute: RoomsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
